project:
  type: book

execute:
  freeze: auto

book:
  title: "Island Biology DAISIE Practical"
  chapters:
    - index.qmd
    - installation.qmd
    - introduction.qmd
    - assignment.qmd
    - DAISIEprep.qmd
    - DAISIE.qmd
    - exercise.qmd
    - answers.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
